CREATE TABLE Client (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  Name VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  PhoneNumber VARCHAR(255) NOT NULL,
  WhatsappNumber VARCHAR(255) NOT NULL,
  Identifiant VARCHAR(255) NOT NULL,
  Adress VARCHAR(255) NOT NULL,
  IsClientEnGros BIT NOT NULL,
  DateCreated DATETIME2 NULL,
  CreatedBy VARCHAR(255) NULL,
  DateModified DATETIME2 NULL,
  ModifiedBy VARCHAR(255) NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Fournisseur (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  Name VARCHAR(255) NOT NULL,
  Identifiant VARCHAR(225) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  WhatsappNumber VARCHAR(255) NOT NULL,
  DateCreated DATETIME NULL,
  CreatedBy VARCHAR(255) NULL,
  DateModified DATETIME NULL,
  ModifiedBy VARCHAR(255) NULL,
  PRIMARY KEY (Id)
);